java-service:
  replicaCount: 1
  fullnameOverride: "greeting-service"
  image:
    repository: "hycomcminternal.azurecr.io/greeting-service" # Będzie ustawiane przez workflow
    tag: "23f5275" # Placeholder - będzie nadpisywane
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  serviceAccountName: "greeting-service-sa"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  env:
    - name: AZURE_KEYVAULT_URL
      value: "https://hycomcminternal-kv.vault.azure.net"
    - name: AZURE_STORAGE_ACCOUNT_NAME
      value: "hycomcminternal"
    - name: AZURE_STORAGE_CONTAINER_NAME
      value: "test-container-dev"
